### ISSUE TITLE
Bug for file based backends

### ISSUE THREAD

**Issue by giagiannis** [giagiannis/docker-layer-encryption#1]
When setting the file backend and executing:

`bin/idle-at-rest-client setup -c <id>`

The following trace appears:

```
Traceback (most recent call last):
  File "bin/idle-at-rest-client", line 65, in <module>
    succeeded = client.setup(passphrase)
  File "/usr/local/lib/python2.7/dist-packages/idle-0.1-py2.7.egg/idle/client.py", line 114, in setup
    return self.__driver.setup(passphrase)
  File "/usr/local/lib/python2.7/dist-packages/idle-0.1-py2.7.egg/idle/core.py", line 254, in setup
    if not super(FileAtRestEncryptionDriver, self).setup(passphrase):
  File "/usr/local/lib/python2.7/dist-packages/idle-0.1-py2.7.egg/idle/core.py", line 149, in setup
    if self.get_status()!=BaseAtRestEncryptionDriver.Status.UNENCRYPTED:
  File "/usr/local/lib/python2.7/dist-packages/idle-0.1-py2.7.egg/idle/core.py", line 275, in get_status
    if not path.isfile(self._get_disk_file()):
  File "/usr/local/lib/python2.7/dist-packages/idle-0.1-py2.7.egg/idle/core.py", line 324, in _get_disk_file
    return self.__docker_driver.get_topmost_layer_path(data=False)+".disk"
AttributeError: 'FileAtRestEncryptionDriver' object has no attribute '_FileAtRestEncryptionDriver__docker_driver'
```

**Comment by giagiannis** [comment]
The __docker_driver object was not transparent to the FileAtRestEncryptionDriver. It now became public.
